[package]
name = "async-in-rust"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
mini-redis = "0.4.1"
bytes = "1.4.0"
crossbeam = "0.8.2"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]
